import Provider from './components/Provider'
import Header from './components/Header'
import Footer from './components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next13 App with auth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html 
      lang="en"
      className={'${inter.className} h-full scroll-smooth antialilsed'}
    >
      <body className= 'flex h-full flex-col'>
        <Provider>
          <Header />
            <main className='grow'>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
